### ISSUE TITLE
Kraken1 database exit code 137

### ISSUE THREAD

**Issue by lskatz** [DerrickWood/kraken#155]
Hi, I am trying to put Kraken1 into a GitHub actions and keep running into this error.  Any ideas for how to fix it?  Thank you!

Bigger context:
https://github.com/lskatz/Kalamari/runs/3138121186?check_suite_focus=true#step:13:123

```
  kraken
├── library
│   └── added
│       ├── KSki6qyEb3.fna
│       ├── KTgKFRZsjx.fna
│       └── prelim_map.txt
└── taxonomy
    ├── names.dmp
    └── nodes.dmp

3 directories, 5 files
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.12
Hash size not specified, using '6849280'
K-mer set created. [1.502s]
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
/home/runner/work/Kalamari/Kalamari/kraken-1.1.1/kraken-src/build_kraken_db.sh: line 155:  2886 Killed                  db_sort -z $MEMFLAG -t $KRAKEN_THREAD_CT -n $KRAKEN_MINIMIZER_LEN -d database.jdb -o database.kdb.tmp -i database.idx
Error: Process completed with exit code 137.
```

**Comment by DerrickWood** [comment]
Hi @lskatz - Judging from the output you've shown, this is a small amount of sequence data for a Kraken database. You might want to try adjusting the minimizer length to something smaller than the default if you haven't already. There might be an issue within the sorting step that has trouble with empty minimizer bins (although I'm only guessing - it's been quite a while since I've tried a small DB with Kraken 1).

**Comment by lskatz** [comment]
Thank you!  This seems to have fixed the build step!  I tried a minimizer length of 9 as a start and it worked! https://github.com/lskatz/Kalamari/runs/3194952916?check_suite_focus=true#step:13:162
