### ISSUE TITLE
Pair end reads problem

### ISSUE THREAD

**Issue by davidmartinad200** [DerrickWood/kraken#24]
kraken --paired --fastq-input --gzip-compressed -db /db/kraken   --threads 1  --out  --classified-out kraken_out  file.R1.gz file.R2.gz
kraken: --paired requires exactly two filenames

Ok now added a colon between the two files as follows:
kraken --paired --fastq-input --gzip-compressed -db /db/kraken   --threads 1  --out  --classified-out kraken_out  file.R1.gz,file.R2.gz

read_merger.pl: kraken_out does not exist
classify: malformed fasta file - expected header char > not found
0 sequences (0.00 Mbp) processed in 0.000s (0.0 Kseq/m, 0.00 Mbp/m).
0 sequences classified (-nan%)
0 sequences unclassified (-nan%)

**Comment by DerrickWood** [comment]
This is an issue with the command line options you're using.  The --out switch is a shortened version of the --output switch, which has a mandatory filename argument. Because you're omitting that argument, the filename is considered to be the next string token ("--classified-out"), which isn't what you want. This causes a second problem, as in the first example, the command now thinks there are three input files ("kraken_out", "file.R1.gz", "file.R2.gz"), and in the second example, that there are two ("kraken_out", "file.R1.gz,file.R2.gz").

The simple solution here is to either provide a filename for the normal Kraken output, or use "-" as that filename to suppress that output. Then the command should be parsed correctly.

**Comment by davidmartinad200** [comment]
Thanks,
Worked this way.
kraken --fastq-input  --gzip-compressed -db /db/kraken  --paired  --check-names --threads 20  file.R1.gz file.R2.gz

**Comment by zeliy90** [comment]
Hi Im a bit of a novice to this but I was wondering how you would approach this if you has a folder of pair-end reads and just wanted kraken2 to loop through them like in python it would be
for i in (folder of reads):
    and then you would input i and i+1 (paired files) into your kraken2 command
