### ISSUE TITLE
fastq detection fails when paired reads

### ISSUE THREAD

**Issue by lpantano** [DerrickWood/kraken#7]
Hi,

I have an error when I use paired reads that are in fast files. I think that maybe is missing something in the parsing options when paired is set up.

```

 /home/lp113/soft/bin/kraken --paired --db /home/lp113/soft/kraken/db/minikraken_20140330 --quick  --preload --min-hits 3 --threads 1 --out - --classified-out kraken_out /home/lp113/bcbio-nextgen/tests/test_automated_output/trim/Hsapiens_Mmusculus_1_trimmed.fq /home/lp113/bcbio-nextgen/tests/test_automated_output/trim/Hsapiens_Mmusculus_rep2_trimmed.fq 
Loading database... read_merger.pl: mismatched mate pair names ('HWI-ST1233:94:C0YE6ACXX:2:1302:19463:27765' & 'HWI-ST1233:94:C0YE6ACXX:2:1302:19463:27765g')
complete.
classify: malformed fasta file - expected header char > not found
0 sequences (0.00 Mbp) processed in 0.000s (0.0 Kseq/m, 0.00 Mbp/m).
  0 sequences classified (-nan%)
  0 sequences unclassified (-nan%)

```

**Comment by tseemann** [comment]
@lpantano I think this is a problem with the ```read_merger.pl``` script.

Illumina used to put a ```/1``` and ```/2``` suffix on paired end reads, but now they use a different syntax with a space in it ```<space>1:N:0:2``` and ```<space>2:N:0:2``` or similar.

**Comment by lpantano** [comment]
thanks @tseemann , makes a lot of sense. it would be good a fix, when i run this is inside a pipeline and not willing to parse the file :) for now using only one of the reads. thanks so much!

**Comment by DerrickWood** [comment]
Although `read_merger.pl` is indeed the script that's generating the error, this isn't due to the change @tseemann is mentioning. The `read_merger.pl` script actually only focuses on the first whitespace-separated string (the read ID) in the header, so the `<space>1:N:0:2` wouldn't even be considered when checking the read IDs. The `/1` and `/2`, if present, would have been removed by the script before comparing read IDs, so that would have been ok as well.

In the particular example @lpantano gives, the two read IDs that the script is complaining about are `HWI-ST1233:94:C0YE6ACXX:2:1302:19463:27765` and `HWI-ST1233:94:C0YE6ACXX:2:1302:19463:27765g`. The addition of a "g" in the second read ID isn't expected, as it's not a known method to indicate paired reads, and causes the merger to abort. (Note that any `/1`, `_1`, or `.1` at the end of the actual read ID would have been removed by the script prior to emitting this error message, so the reported read IDs here may not be exactly what are in the FASTQ files.)

I'm thinking I may just add an option to turn off read name checking (or even make that the default operation and require name checking to be explicitly requested) so that any new syntax for paired-end reads that comes up can at least be worked past here by users.

**Comment by DerrickWood** [comment]
The default operation will now avoid checking names; if you want this turned on, you can explicitly request it using `--check-names` in addition to `--paired`.

**Comment by lpantano** [comment]
thanks u so much.

**Comment by zhq90** [comment]
### I have a similar issue.
**The command line:**
 "kraken --db $database--fastq-output --paired --check-names --out-fmt paired --unclassified-out unclassified --classified-out classified --output kraken.result --fastq-input CL100071231_L01_67_unmapped_1.fq CL100071231_L01_67_unmapped_2.fq" 

`read_merger.pl: malformed fastq file (line = '@CL100071231L1C001R002_49/1')`

@DerrickWood
