### ISSUE TITLE
Problems compiling Kraken under MacOS 10.12

### ISSUE THREAD

**Issue by ckehlmaier** [DerrickWood/kraken#97]
Hello,
When executing the ./install_kraken.sh under MacOS 10.12 the following error message pops up:

g++ -Wall -fopenmp -O3 -c krakendb.cpp
clang: error: unsupported option '-fopenmp'
make: *** [krakendb.o] Error 1

Any suggestion?
Cheers!

**Comment by kliere** [comment]
I like to chime in here. Same error on macOS.

**Comment by DerrickWood** [comment]
This is related to MacOS's strange decision to not include OpenMP as part of its default GCC installation. OpenMP is a requirement for Kraken - you'll need to install a version of GCC that does include it. See https://groups.google.com/d/msg/kraken-users/0i2m81J_1uw/_zk1zUB3npsJ for some instructions toward one path for doing that installation.

**Comment by ExplodingCabbage** [comment]
Since the Google Groups link is broken, some instructions for any future readers struggling with this:

* Install [Brew](https://brew.sh/)
* Run `brew install gcc`

You'll now have the latest release version of GCC and G++ installed. However, Brew does *not* overwrite the default macOS `gcc` and `g++` binaries. Instead, it creates numbered binaries that exist in parallel. Since at the time of writing the current release version of GCC is GCC 9.1, you'll be able to run the Brew-installed versions with `gcc-9` and `g++-9`.

* Clone the Kraken repo
* Open `kraken/src/Makefile` and change the first line from `CXX = g++` to `CXX = g++-9`

(I think the convention is not to set CXX inside a Makefile, but instead to rely on the implicit default of `g++` and allow users to override it with an environment variable. But since it gets explicitly set in the Makefile here, we've got no choice but to modify the Makefile.)

* Finally, run `./install-kraken.sh /dir/to/install/to`

**Comment by Jeremieauger** [comment]
Tried this MakeFile edit and had no luck. But from another post, seems brew is working!
From: https://github.com/DerrickWood/kraken2/issues/734
brew install kraken2
